# Generated by Django 4.2.3 on 2023-07-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producturl',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
